### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by kaffetorsk** [dceejay/RedMap#196] opened 2022-04-08 08:07 UTC
Hi,
1 bug and 1 question related to heatmap.

1. (question) It seems that heatmap is only generated per session, so if I refresh the page, or open a new session the heatmap resets. Is this intended behaviour? If it is, I would request some mechanism to aggregate the heatmap server side.

2. (bug) If i turn on the heatmap layer, then turn it off again, the tracks disappear after next position update, even though they are in separate layers. After this initial cycling of the heatmap layer, the tracks will only show if heatmap is shown. The bug has to be cleared by refreshing the page.

**Comment by dceejay** [comment] 2022-04-08 09:20
1) Yes it is as designed... Happy to look at a pull request if you want to add aggregation somehow.
2) Not sure what you mean - do you have an example flow/screenshots ?

**Comment by kaffetorsk** [comment] 2022-09-08 19:50
Added PR #203

**Comment by dceejay** [comment] 2022-09-08 21:05
Thanks - will have a look.

**Comment by devleaks** [comment] 2022-12-16 08:44
Well, I had the same issue but it is not too difficult to solve. The reason is that points in the heatmap are kept into the heatmap plugin. Fortunately, thanks to solving issue #218, it is now possible to keep the array of (lon,lat) yourself (in db, in session, etc.) and send it to heatmap for display.
Of course, you have to keep/manage the array of positions yourself, but it is not too difficult. P.

**Comment by dceejay** [comment] 2022-12-16 17:31
Closing due to heatmap update that lets user replace complete heatmap array.

**Closed by dceejay** 2022-12-16 17:31 UTC
Labels: needs more info
